# Generated by Django 4.0.3 on 2022-04-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
    ]
