# Generated by Django 4.0.3 on 2022-04-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0003_profile_owner_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
